build.sbt
domain-classes-generator/src/main/scala/flatgraph/codegen/CodeSnippets.scala
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/Accessors.scala
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/Cpg.scala
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/GraphSchema.scala
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/Languages.java
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/NodeTypes.java
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/PropertyNames.java
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/Traversals.scala
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/nodes/TypeDecl.scala

* e.g. Expression.orderNot - to match what overflowdb generated
* also note that I reversed (fixed) the logic for two of the 'equals' cases

generate traversal filter steps for 'property does not equal'

---

core/src/main/scala/flatgraph/storage/Deserialization.scala
core/src/main/scala/flatgraph/storage/Serialization.scala
odb-convert/src/main/scala/flatgraph/convert/Convert.scala

also: use with absolute filenames, otherwise 'file.exists' and friends
don't work

Convert: create target file if it doesn't yet exist

---

core/src/main/scala/flatgraph/DiffGraphApplier.scala
core/src/main/scala/flatgraph/Graph.scala
core/src/main/scala/flatgraph/misc/TestUtils.scala
core/src/test/scala/flatgraph/GraphTests.scala
core/src/test/scala/flatgraph/TestHelpers.scala
core/src/test/scala/flatgraph/util/DiffToolTests.scala

Alternative proposal to https://github.com/joernio/flatgraph/pull/162
I moved a few things around and refactored for readability. Main difference in API is that rather than
`graph.copyDataFrom(other: Graph)` 
this does
`graph.copy(): Graph`

add functionality to clone graphs (important for unit test performance)

---

benchmarks/src/main/scala/flatgraph/benchmark/LoadingAndMemoryBenchmarks.scala
core/src/main/scala/flatgraph/Accessors.scala
core/src/main/scala/flatgraph/DiffGraphApplier.scala
core/src/main/scala/flatgraph/Graph.scala
core/src/main/scala/flatgraph/Schema.scala
core/src/main/scala/flatgraph/misc/DebugDump.scala
core/src/main/scala/flatgraph/misc/TestUtils.scala
core/src/main/scala/flatgraph/storage/Deserialization.scala
core/src/main/scala/flatgraph/storage/Serialization.scala

* same naming for properties: should also be propertyKinds
* centrally encode the fact that our ranges are 0.until(numberOfXyzKind)
in the schema, not distrubuted across all usage sites

unify node|edge|property kind ranges in schema

---

domain-classes-generator/src/main/scala/flatgraph/codegen/DomainClassesGenerator.scala

n.b. regenerating the domain classes with this has a dependency
resolution issue, it picks the old codegen. Not sure why, but since we
don't really need the full cpg domain classes committed here I'll take
that as a trigger to setup a simplified sample schema here which is
independent of cpg...

fixup: on last PR i forgot to update the codegen

---

core/src/main/scala/flatgraph/DiffGraphApplier.scala
core/src/main/scala/flatgraph/Graph.scala
core/src/main/scala/flatgraph/Schema.scala
core/src/main/scala/flatgraph/misc/Conversions.scala

also: fix array kind bounds check

fix toShortSafely: yes we can safely convert -1 to short :)

---

domain-classes-generator/src/main/scala/flatgraph/codegen/DomainClassesGenerator.scala
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/GraphSchema.scala
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/neighboraccessors/Call.scala
joern-generated/src/main/scala/io/shiftleft/codepropertygraph/generated/neighboraccessors/MethodReturn.scala

This part of the codegen was different to overflowdb up until now, and
unfortunately problems only became evident when porting codescience.
Specifically: `MethodReturn.cfgIn` must return an `Iterator[CfgNode]`, rather
than an `Iterator[Return]` as it was before this PR.

neighbor types: take inherited neighbors into account

---

build.sbt
core/src/main/scala/flatgraph/DiffGraphApplier.scala
core/src/main/scala/flatgraph/DiffGraphBuilder.scala
core/src/main/scala/flatgraph/misc/SchemaViolationReporter.scala
core/src/main/scala/flatgraph/traversal/Language.scala
core/src/test/scala/flatgraph/DiffGraphTests.scala
domain-classes-generator/src/main/scala/flatgraph/codegen/DomainClassesGenerator.scala
domain-classes-generator/src/main/scala/flatgraph/codegen/Helpers.scala
test-schemas-domain-classes/src/main/scala/flatgraph/testdomains/generic/PropertyErrorRegister.scala
test-schemas-domain-classes/src/main/scala/flatgraph/testdomains/gratefuldead/PropertyErrorRegister.scala
tests/src/test/scala/flatgraph/GraphTests.scala
tests/src/test/scala/flatgraph/testutils/TestHelpers.scala

Illegal usage of node properties often roots in deserialising an old
storage format, so we don't want to error out but rather log a warning, and
only do so once for each node/property combination.

schema-conflicting node properties: only warn, don't error

---

project/build.properties
sbt-flatgraph/src/main/scala/flatgraph/codegen/sbt/FileUtils.scala
sbt-flatgraph/src/main/scala/flatgraph/codegen/sbt/FlatgraphCodegenSbtPlugin.scala

* don't fail for nonexisting inputs
* allow to add more inputs in the build via a custom setting
* add build's /built.sbt to the default inputs

codegen cache fixes

---

core/src/main/scala/flatgraph/storage/Deserialization.scala
core/src/main/scala/flatgraph/storage/Serialization.scala
core/src/main/scala/flatgraph/storage/package.scala
odb-convert/src/main/scala/flatgraph/convert/Convert.scala

* unix `file` util reports `data` as type
* `cat` and friends print `FLT GRPH...`

change file header to less common and easier detectable magicbytes

---

core/src/main/scala/flatgraph/storage/Deserialization.scala

before:
```
expected header (`[B@75c274f1`), but found 12249
```
now:
```
expected header 'FLT GRPH' (`7076843271828072`), but found '1234-97000'
```

improve error message for unexpected header

---

README.md
core/src/main/java/flatgraph/GNode.java
core/src/main/scala/flatgraph/misc/DebugDump.scala
core/src/test/scala/flatgraph/util/DiffToolTests.scala

As requested @ml86 
Ideally we'd use the intellij annotation stuff to avoid having to manually configure out IDEs (we would pull in the annotations as dependency, but no actual code). Unfortunately I couldn't get that to work :(

add structured debug representation

---

core/src/main/scala/flatgraph/Graph.scala

One of our scripts started failing once we upgraded to flatgraph because of a previously-unexpected `initialising from existing storage ...` message. Does it make sense to replace that `println` for a logger message? ~I took this opportunity to look for some more `println` calls and replaced those that I thought would fit as logs.~ EDIT: I was being overzealous, and reverted them once I noticed these were behind a verbose flag.

use logger instead of println

---

core/src/main/scala/flatgraph/DiffGraphApplier.scala
core/src/test/scala/flatgraph/GraphTests.scala
tests/src/test/scala/flatgraph/GraphTests.scala

With this, the diffgraph applier again counts the number of transitive modifications in the graph, in order to restore the logging.
Furthermore this restores the correct order of nodes that are transitively added -- we need to `drainDeferred` after every single update, not just at the end. This behavior was a little subtle and was missing both tests and a comment explaining it, so it got lost in a refactor (cf git blame). Now it's protected by both source-code comment and unit test.

Make diffgraph applier return number of transitive changes

---

domain-classes-generator/src/main/scala/flatgraph/codegen/CodeSnippets.scala

The code snippet generated with `FilterSteps#genericOption` results in an error like the one below during compilation.
```
value || is not a member of Iterable[Long @uncheckedVariance]
```
Replacing `.empty` with `.isEmpty` should fix this.

Fix generated code snippet for property traversal

---

build.sbt

We migrated to sonatype central due to publishing problems, as
suggested by their support. Let's see if this works.
https://central.sonatype.com/

sonatype central

---

build.sbt

the default sbt naming convention for plugins does not conform to the
maven specification - see https://github.com/sbt/sbt/issues/3410

sonatype publishing fix for sbt plugin

---

README.md
core/src/main/scala/flatgraph/storage/Deserialization.scala
core/src/main/scala/flatgraph/storage/Serialization.scala
core/src/main/scala/flatgraph/storage/ZstdWrapper.scala

zstd requires a tmp dir without the `noexec` flag - probe for that and
inform the user about their options

check tmp dir for noexec flag and warn user

---

core/src/main/scala/flatgraph/storage/Serialization.scala
core/src/test/scala/flatgraph/SerializationTests.scala

prior to this change, the test would fail with:
```
java.io.FileNotFoundException: /tmp/foo/bar (No such file or directory)
at java.base/java.io.RandomAccessFile.open0(Native Method)
at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
at flatgraph.storage.Serialization$.writeGraph(Serialization.scala:23)
```

storage: create parent directories if they don't exist

---

.github/workflows/pr.yml
.github/workflows/release.yml

sbt is no longer included by default in the ubuntu 24 runner
https://github.com/sbt/setup-sbt
https://github.com/actions/setup-java/issues/712#issuecomment-2557396980

fix github actions

---

core/src/main/scala/flatgraph/storage/Serialization.scala
core/src/test/scala/flatgraph/SerializationTests.scala

`java.nio.Path::getParent` returns `null` if the path is the root
directory already, so trying to create the root's parent directory both
fails hard and doesn't make any sense

serialization: handle 'null' value from java's File.getParent api

---

test-schemas-domain-classes/src/main/scala/testdomains/codepropertygraphminified/traversals/TraversalCallBase.scala
test-schemas-domain-classes/src/main/scala/testdomains/codepropertygraphminified/traversals/TraversalCallreprBase.scala
test-schemas-domain-classes/src/main/scala/testdomains/codepropertygraphminified/traversals/TraversalDeclarationBase.scala
test-schemas-domain-classes/src/main/scala/testdomains/codepropertygraphminified/traversals/TraversalPropertyDispatchType.scala
test-schemas-domain-classes/src/main/scala/testdomains/codepropertygraphminified/traversals/TraversalPropertyName.scala
test-schemas-domain-classes/src/main/scala/testdomains/generic/traversals/TraversalNodeaBase.scala
test-schemas-domain-classes/src/main/scala/testdomains/generic/traversals/TraversalPropertyStringMandatory.scala
test-schemas-domain-classes/src/main/scala/testdomains/gratefuldead/traversals/TraversalArtistBase.scala
test-schemas-domain-classes/src/main/scala/testdomains/gratefuldead/traversals/TraversalPropertyName.scala
test-schemas-domain-classes/src/main/scala/testdomains/gratefuldead/traversals/TraversalSongBase.scala
test-schemas-domain-classes/src/main/scala/testdomains/hierarchical/traversals/TraversalBasenodeBase.scala
test-schemas-domain-classes/src/main/scala/testdomains/hierarchical/traversals/TraversalPropertyName.scala

oops, check in generated code for test-schemas. Amends #297 / a64ce01000bc490fa83be47e9fc19c94658c7e9e

Check in generated code for test-schemas. Amends #297

---

odb-convert/src/main/scala/flatgraph/convert/Convert.scala

Another oops: We don't have unit tests in this repo for legacy odb conversion. Last PR broke that, and I only noticed in the codepropertygraph repo when bumping deps...
So this PR needs to go in to unbreak that. Afterwards: How do we want to deal with the unit test situation?
1. Write new tests here
2. copy/move over tests from the other repo
3. document that this is an issue, so that we know to run that test next time we touch serialization code

fix up legacy odb conversion

---

build.sbt
domain-classes-generator/src/main/scala/flatgraph/codegen/DomainClassesGenerator.scala
test-schemas-domain-classes/src/main/scala/testdomains/codepropertygraphminified/traversals/package.scala
test-schemas-domain-classes/src/main/scala/testdomains/empty/traversals/package.scala
test-schemas-domain-classes/src/main/scala/testdomains/generic/traversals/package.scala
test-schemas-domain-classes/src/main/scala/testdomains/gratefuldead/traversals/package.scala
test-schemas-domain-classes/src/main/scala/testdomains/hierarchical/traversals/package.scala

Projects that are used as libraries should stick to the latest LTS version.
Scala 3 guarantees backward compatibility across minor releases in the entire 3.x series, but no
t forward compatibility. This means that libraries compiled with any Scala 3.x version can be used
in projects compiled with any Scala 3.y version with y >= x.
https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html#library-maintainers
https://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html

downgrade to scala 3.3 LTS

---

core/src/main/scala/flatgraph/storage/Deserialization.scala
core/src/test/scala/flatgraph/SerializationTests.scala

re https://github.com/joernio/flatgraph/security/advisories/GHSA-jqmx-3x2p-69vh
n.b. it is not our goal to have a "safe" file format, and we need to
document that properly. But adding some more straightforward checks
doesn't harm.

Deserialization: verify manifest size

---

README.md

This adds some clarifications regarding security goals. Big thanks to https://github.com/xavierpinho :heart: for mentioning that here  https://github.com/joernio/flatgraph/security/advisories/GHSA-jqmx-3x2p-69vh
Any improvement / rewording ideas?

add some docs regarding security
